### ISSUE TITLE
Preloader feature addition

### ISSUE THREAD

**Issue by Sypher0Dronzer** [sethshivam11/college-management#21]
I wish to add a preloader to the website which improves user experience as they wait for the site to load.

Please assign this issue to me @sethshivam11

**Comment by sethshivam11** [comment]
@Sypher0Dronzer What type of preloader are you thinking to implement?

Please note: The site https://campus-space.onrender.com takes 50 seconds to load because render has a setup in which if no inbound traffic is there then it will spin off the server and the server will be spun again for new requests.

**Comment by Sypher0Dronzer** [comment]
https://github.com/sethshivam11/campus-space/assets/83546205/0d58a614-d702-4c64-82c9-ade2bc491075

This is the preloader that I have in mind for the website. Its something people would like to watch while they wait. Its catchy and elegant.

I have other alternatives as well such as this 

https://github.com/sethshivam11/campus-space/assets/83546205/2a05fddb-ca84-41f6-968a-db28193d58fb

@sethshivam11 incase you need other alternatives please let me know

**Comment by sethshivam11** [comment]
@@Sypher0Dronzer I don't think these loaders will work, because these are much different from the overall theme.

**Comment by Sypher0Dronzer** [comment]
How about a normal rotation preloader

**Comment by sethshivam11** [comment]
@Sypher0Dronzer I don't think there is a need because the page is loading fast, and doesn't require one.
